CREATE DATABASE IF NOT EXISTS microServicesLogindb;

USE microServicesLogindb;

CREATE TABLE IF NOT EXISTS roles (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL
);

INSERT IGNORE INTO roles(name) VALUES ('ROLE_USER');
INSERT IGNORE INTO roles(name) VALUES ('ROLE_ADMIN');
